application: chromedevsummit-site-2016
version: v20161019

runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: /devsummit/static/third_party/(.*)
  static_files: static/third_party/\1
  expiration: "1d"
  upload: static/third_party/(.*)
  secure: always

- url: /devsummit/static/images/(.*)
  static_files: static/images/\1
  expiration: "1d"
  upload: static/images/(.*)
  secure: always

- url: /devsummit(.*)
  script: main.app
  secure: always

- url: /devsummit/LICENSE
  static_files: dist/LICENSE
  expiration: "7d"
  mime_type: text/plain
  upload: dist/LICENSE
  secure: always

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
